### ISSUE TITLE
CTA #2

### ISSUE THREAD

**Issue by pelletism** [eisenfox/soldags#19]
Some things with the CTA under the headline "Funkar solkraft för dig?". First, use this text in the paragraph: 
//TEXT//
Varje hus har sina individuella förutsättningar för solkraft. För att få reda på hur bra solkraft funkar med ditt hus, krävs några timmars räknande. Det kan du naturligtvis göra själv, men det enklaste sättet att göra det, är att låta oss göra jobbet. 
Fyll i ditt postnummer här nedan så får du direkt svar på om du bor rätt för solkraft. 
Vill du sedan veta mer, kan vi ordna en detaljerad kalkyl inom 24 timmar, helt utan kostnad. 

//FIELD//
Postnummer

//BUTTON//
Kolla läget

//TEXT IN MODAL POPPING UP FROM BUTTON. 4 ALTERNATIVE TEXTS//
Du har mycket goda förutsättningar för solenergi. //
Du har goda förutsättningar för solenergi. //
Du har hyfsade förutsättningar för solenergi. //
Du har dåliga förutsättningar för solenergi. //

Vill du ha en detaljerad kalkyl för ditt eget tak? 
Lämna dina kontaktuppgifter nedan så återkommer vi med en prognos inom 24 timmar.

//FIELDS//
Gatuadress:
Postort:
Telefonnummer:
Epost:

**Comment by eisenfox** [comment]
Solved (except alternative text changing, Denis will do it)
