### ISSUE TITLE
Text at CTA#1

### ISSUE THREAD

**Issue by pelletism** [eisenfox/soldags#20]
TEXT FOR THE FIRST MODAL, AT "TELL ME MORE"
• Change "Tell me more" to "Jag vill veta mer"
• In the modal, please use text: 

//HEADLINE//
En preliminär solstyrka
//TEXT//
Vi kan göra en preliminär beräkning av hur lönsamt solenergi vore för ditt tak utifrån fem faktorer, bland annat geografiskt läge, hur stort ditt tak är och i vilket väderstreck det ligger. Lämna dina kontaktuppgifter nedan så återkommer vi med en prognos inom 24 timmar. 
//FIELDS//
Gatuadress:
Postort:
Telefonnummer:
Epost:
---------------------
FYI, this is what the text above says (Google Translate version)

"A preliminary sun strength
//TEXT//
We can make a preliminary calculation of how profitable solar energy would be for your roofs based on five factors, including geographic location, how big your roof is and in what weather it is. Leave your contact details below and we will return with a forecast within 24 hours.
//FIELDS//
Street Address:
city:
Phone number:
E-mail:"
-------------------

**Comment by eisenfox** [comment]
Solved
