### ISSUE TITLE
Contact us text in the footer

### ISSUE THREAD

**Issue by pelletism** [eisenfox/soldags#21]
Text for "Kontakta oss" in the bottom

Change "Man request adapted spirits ..." to
Vi finns normalt på plats mellan 08.00 och 17.00. 
För att komma i kontakt med vår installatör samt utanför kontorstid, använd de kontaktuppgifter som finns i ditt avtal.

ADRESS
Almnäsvägen 16, 124 30 Bandhagen
TELEFON
+46 70 597 80 88

//FIELDS//
Namn*
Epost *
Telefon (frivilligt)

Ditt meddelande*

//BUTTON//
Skicka

**Comment by eisenfox** [comment]
Chaged
