### ISSUE TITLE
Change image/map

### ISSUE THREAD

**Issue by pelletism** [eisenfox/soldags#22]
We've updated the map image to make it a bit more clear. Please change the existing map image to the attached one, cut and size as is on webpage today. (you get two versions, since I'm not sure which size-version you use today.)  
[https://www.dropbox.com/s/8zp4pvgo9oqvtbm/sw-map-small-mod2.pdf?dl=0](url)
[https://www.dropbox.com/s/2645rccg7dk5cdn/sw-map-mod2.pdf?dl=0](url)

**Comment by eisenfox** [comment]
Solved
