### ISSUE TITLE
Postnummer logic not implemented

### ISSUE THREAD

**Issue by AndersOlsson123** [eisenfox/soldags#23]
When entering Postnummer on homepage and clicking on "Kolla läget" the following should happen:

1. There should be a requirement that there are five digits in PostNummer. Spaces are also OK to include
2. The message should vary based on the first two digits entered. So if user enters PostNummer 14523, then message should be based on first two digits: 14
3. Here is a list of numbers, and what message should be:
Alternative 1: If it is {10-15,18,20-23,25-26,37-39,62} message should be: Du ser ut att bo i ett område med utmärkta förutsättningar för solkraft!
Alternative 2: If it is {16-17,19,24,27-32,35-36,40-61,63-78} message should be: Du ser ut att bo i ett område med goda förutsättningar för solkraft!
Alternative 3: If it is {28,33,34,79-82,84-89} message should be: Du ser inte ut att bo i ett av de områden med bäst förutsättningar för solkraft!
Alternative 4: If it is {83,90-99} message should be: Du ser ut att bo i ett område med svag solstrålning!
Alternative 5: Any other numbers message should be: Vi har inga uppgifter på det området tyvärr.
If Alternative 1 or 2 user can enter data as before.
If Alternative 3 to 5 there should be an additional message: "Vi kan tyvärr ej göra någon prognos för din region i dagsläget. Fyll i uppgifter nedan så hör vi av oss när det blir aktuellt." (and user can enter data as before).

**Comment by eisenfox** [comment]
Postnummer logic will be fully implemented only in Wordpress version (today or tomorrow, I hope), as we discussed previously =)

**Comment by Rainfall** [comment]
Wordpress logic ready for that task

**Comment by eisenfox** [comment]
HTML website logic is implemented too (included Per's task https://github.com/eisenfox/soldags/issues/19)
