### ISSUE TITLE
Need i miniicon for soldags webpage

### ISSUE THREAD

**Issue by AndersOlsson123** [eisenfox/soldags#38]
We need a "miniicon" that shows up in tabs at the very top of page (on Natalis prototype page Natali used the S from logo with shadow).  Use the yellow sun from soldags logo for now (but slightly bigger).

**Comment by eisenfox** [comment]
@AndersOlsson123 check it please on HTML prototype (http://eisenpar.com/soldags/blog.php), but clean the cache first. if you like it, I'll send new favicon to Denis

**Comment by AndersOlsson123** [comment]
Looks good!

**Comment by eisenfox** [comment]
@AndersOlsson123 awesome! it will be on the Wordpress version soon!

**Comment by eisenfox** [comment]
@AndersOlsson123 Check please Wordpress version, but clear your cache before! 

Solved
