### ISSUE TITLE
Strange behaviour when entering e-mail adress with incorrect format - see picture (poor error message, and it ends up in the wrong place) 

### ISSUE THREAD

**Issue by AndersOlsson123** [eisenfox/soldags#39]
![image](https://user-images.githubusercontent.com/29488637/27898103-91f7bf4c-6224-11e7-9317-04d5049a0855.png)

**Comment by eisenfox** [comment]
@AndersOlsson123 it's a task for Denis, I'll send it to him

**Comment by Rainfall** [comment]
Also fixed =)

**Comment by AndersOlsson123** [comment]
Now when I enter and press "Kolla läget" button - nothing happens!

**Comment by Rainfall** [comment]
Fixed!

**Comment by eisenfox** [comment]
Solved
