### ISSUE TITLE
Error message ends up in the wrong place when leaving Gatuadress blank (see picture)

### ISSUE THREAD

**Issue by AndersOlsson123** [eisenfox/soldags#40]
![image](https://user-images.githubusercontent.com/29488637/27898168-ed854c3a-6224-11e7-8f1e-ec1275944b5e.png)

**Comment by eisenfox** [comment]
@AndersOlsson123 it's a task for Denis, I'll send it to him

**Comment by Rainfall** [comment]
Fixed

**Comment by eisenfox** [comment]
Solved
