### ISSUE TITLE
All fields filled in correctly, but I still get an error message (see image) - perhaps this only happens after I've previously done something else wrong

### ISSUE THREAD

**Issue by AndersOlsson123** [eisenfox/soldags#41]
![image](https://user-images.githubusercontent.com/29488637/27898232-51d2337e-6225-11e7-8641-27b92dd4443a.png)

**Comment by Rainfall** [comment]
Tel number is not actually a number. So you have to fix it. Alternatively I could make this field as just text, not tel

**Comment by AndersOlsson123** [comment]
Good point.  Then it is the error message that should be changed.  Generic error messages like "One or more fields have an error." are not user friendly.  A correct error message needs to appear right under the "Telefonnummer" text field.

**Comment by eisenfox** [comment]
@AndersOlsson123 This is a task for Denis, I'll send it to him

**Comment by Rainfall** [comment]
Should be fixed now

**Comment by eisenfox** [comment]
Solved
