### ISSUE TITLE
When "Kolla Läget" modal is filled in and "submitted" no e-mail to anders@soldags.se is generated!

### ISSUE THREAD

**Issue by AndersOlsson123** [eisenfox/soldags#42]

**Comment by AndersOlsson123** [comment]
I tried filling in this form a couple of times through Chrome (no e-mail to anders@soldags.se was generated).  I then filled in the form once from Internet Explorer (and an e-mail was generated).  After that I tried to fill in from Chrome and Internet Explorer, but neither one generated an e-mail).

**Comment by eisenfox** [comment]
@AndersOlsson123 have you tried it on the Wordpress version?

**Comment by eisenfox** [comment]
@AndersOlsson123 it's a task for Denis, I'll send it to him

**Comment by AndersOlsson123** [comment]
What is status with this issue?

**Comment by eisenfox** [comment]
Solved
